version: "3.7"
services:
    app:
        build:
            args:
                user: myuser
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: my-app
        container_name: my-container
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
            - ./custom-php.ini:/usr/local/etc/php/conf.d/custom-php.ini
        networks:
            - my-network
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        networks:
            - my-network
    db:
        image: mysql:8.0
        container_name: my-db
        restart: unless-stopped
        ports:
            - 38080:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - my-network
    nginx:
        image: nginx:alpine
        container_name: my-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - my-network
networks:
    my-network:
        driver: bridge
